---
abstract: 'Text-to-HTML converter with Xatena syntax.'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  Cache::MemoryCache: 0
  Encode: 0
  ExtUtils::MakeMaker: 6.42
  HTML::Parser: 0
  LWP::UserAgent: 0
  Test::HTML::Differences: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Xatena
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Exporter::Lite: 0
  Filter::Util::Call: 0
  HTML::Entities: 0
  LWP::Simple: 0
  List::MoreUtils: 0
  UNIVERSAL::require: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/Text-Xatena.git
version: 0.10
