---
abstract: 'Text-to-HTML converter with Xatena syntax.'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  Cache::MemoryCache: 0
  HTML::Parser: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-Xatena
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Lite: 0
  HTML::Entities: 0
  LWP::Simple: 0
  List::MoreUtils: 0
  UNIVERSAL::require: 0
  URI::Escape: 0
version: 0.02
